image:
  file: .gitpod.Dockerfile

# Command to start on workspace startup
tasks:
  # - init: gh auth login
  # - init: ln -s /workspace/Android-Studio-Gitpod/AndroidStudio4.1-Configuration ~/.config/Google/AndroidStudio4.1
  # - init: ln -s /workspace/Android-Studio-Gitpod/AndroidStudio4.1-Plugins ~/.local/share/Google/AndroidStudio4.1
  # - command: cd /usr/local/android-studio/bin/ && ./studio.sh
  - prebuild: ./gradlew build
  - command: zsh
    
# Ports to expose on workspace startup
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore

github:
  prebuilds:
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
